# Generated by Django 6.0.3 on 2026-03-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_colors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
