# Generated by Django 6.0.3 on 2026-03-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0003_outline_user_outline_visible_to_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_color',
            field=models.CharField(default='#ff0000', max_length=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_opacity',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_width',
            field=models.IntegerField(default=15),
        ),
    ]
