# Generated by Django 6.0.3 on 2026-03-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0004_userprofile_last_color_userprofile_last_opacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
